// Assinaturas
int menu_principal(void);
int clientes(void);
int funcionarios(void);
int pagamentos(void);
int mensalidades(void);
int registrar_acesso(void);
int verifica_opcao_1(int);
int verifica_opcao_2(int);
int verifica_opcao_3(int);
void tela_sobre_o_tema(void);
void tela_equipe(void);