void loop_cpf(char *);
int valida_cpf(char *);
void loop_de_validacao_data(char *);
int bissexto(int);
int dataValida(int, int, int);
int valida_format_data(char *);
void divide_data_inteiro(char *, int *);
void pegaData(int *);
void cal_prox_pagamento(int, int, int, int *);
void cal_atraso_etp2(int, int, int, int *);
int cal_atraso(int, int, int);
void cpf_inteiro(char *);
void loop_fone(char *);
void fone_inteiro(char *);
int valida_dd(char *);
int fone_valida_etp2(char *);